name: Helm Charts PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.3.1
        with:
          command: lint
          config: .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run helm-docs
        run: chmod +x .github/helm-docs.sh && .github/helm-docs.sh

  kubeconform-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://kubernetes.io/releases/
        k8s:
          - v1.20.0
          - v1.21.2
          - v1.22.15
          - v1.23.12
          - v1.24.6
          - v1.25.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run kubeconform
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: chmod +x .github/kubeconform.sh && .github/kubeconform.sh