name: Update chart appVersion

on:
  workflow_dispatch:
    inputs:
      chart:
        description: "name fo chart"
        required: true
      version:
        description: "new appVersion"
        required: true
  repository_dispatch:
    types: [update_chart_version]

jobs:
  check_vars:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check chart
        id: variables
        shell: bash
        env:
          valid: '0-9a-zA-Z\-\_'
        run: |
          if [ ! -d "charts/${{ github.event.inputs.chart }}" ]; then
            echo "Chart ${{ github.event.inputs.chart }} does not exist. Canceling update..."
            exit 1
          else
            if [[ ! "${{ github.event.inputs.version }}" =~ [^$valid] ]]; then
              echo "appVersion does not match regex ${{ github.event.inputs.version }}, canceling update..."
              exit 1
            else
              echo "Chart ${{ github.event.inputs.chart }} found. Update appVersion to ${{ github.event.inputs.version }}"
              exit 0
            fi
          fi

  update_appVersion:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set appVersion and push
        shell: bash
        run: |
          sed -i "s/appVersion: .*/appVersion: ${{ github.event.inputs.version }}/g" charts/${{ github.event.inputs.chart }}/Chart.yaml

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
          git status
          git commit -a -m "update chart ${{ github.event.inputs.chart }} to appVersion ${{ github.event.inputs.version }}"
          git push
